# Generated by Django 5.0.1 on 2026-09-14 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=20)),
                ('local_presencial', models.TextField(blank=True, help_text='Endereço ou local caso seja presencial ou híbrido', null=True)),
                ('vagas_totais', models.PositiveIntegerField()),
                ('carga_horaria_horas', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'db_table': 'eventos',
                'ordering': ['-data_inicio'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('presenca_confirmada', models.BooleanField(default=False)),
                ('data_checkin', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='events.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_inscricoes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'db_table': 'inscricoes',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deletado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Está ativo?')),
                ('codigo_validacao', models.CharField(max_length=64, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('url_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_remover', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='events.inscricao')),
            ],
            options={
                'db_table': 'certificados',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('evento', 'participante'), name='unique_active_inscricao_evento_participante'),
        ),
    ]
