# Generated by Django 5.0.1 on 2026-09-16 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(check=models.Q(('data_fim__gt', models.F('data_inicio'))), name='evento_data_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(check=models.Q(('vagas_totais__gt', 0)), name='evento_vagas_totais_positivas'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(check=models.Q(('carga_horaria_horas__gte', 0)), name='evento_carga_horaria_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(check=models.Q(('tipo__in', ['PRESENCIAL', 'ONLINE', 'HIBRIDO'])), name='evento_tipo_valido'),
        ),
    ]
